# Generated by Django 4.2.4 on 2023-08-16 08:00

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, core.models.StatusMixin, core.models.TimestampedMixin),
        ),
        migrations.CreateModel(
            name="CharacteristicValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=128)),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="characteristic_values",
                        to="core.characteristic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, core.models.StatusMixin, core.models.TimestampedMixin),
        ),
        migrations.CreateModel(
            name="Nomenclature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "characteristics",
                    models.ManyToManyField(
                        related_name="nomenclatures",
                        through="core.CharacteristicValue",
                        to="core.characteristic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, core.models.StatusMixin, core.models.TimestampedMixin),
        ),
        migrations.CreateModel(
            name="NomenclatureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, core.models.StatusMixin, core.models.TimestampedMixin),
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, core.models.StatusMixin, core.models.TimestampedMixin),
        ),
        migrations.CreateModel(
            name="NomenclatureInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.group"
                    ),
                ),
                (
                    "nomenclature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="core.nomenclature",
                    ),
                ),
            ],
            bases=(models.Model, core.models.StatusMixin, core.models.TimestampedMixin),
        ),
        migrations.AddField(
            model_name="nomenclature",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="nomenclatures",
                to="core.nomenclaturetype",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="groups",
                to="core.place",
            ),
        ),
        migrations.AddField(
            model_name="characteristicvalue",
            name="nomeclature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characteristic_values",
                to="core.nomenclature",
            ),
        ),
        migrations.AddField(
            model_name="characteristic",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="characteristics",
                to="core.nomenclaturetype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="characteristicvalue",
            unique_together={("characteristic", "nomeclature")},
        ),
    ]
